config/routes.rb
Rails.application.routes.draw do
get '/parties/checks/' => 'parties#checks'
get '/parties/:id/split/' => 'parties#split'

  resources :parties do
    resources :orders
  end

  resources :admins do
    resources :servers
    resources :menu_items
  end

  resources :menu_items
  resources :servers

  get '/orders/kitchen' => 'orders#kitchen'
  get '/orders/bar' => 'orders#bar'
  get '/menu_items' => 'admins#log_in'
  get '/servers' => 'admins#log_in'
  get '/log_in' => 'admins#log_in'
  post '/sessions/' => 'sessions#create'

  delete '/sessions/' => 'sessions#destroy'
  get '/profile' => 'admins#profile'
  resources :orders
  root 'parties#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  has_many :menuitems
  has_many :servers
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :admin
  has_many :orders, dependent: :destroy
  has_many :parties, through: :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :party
  belongs_to :menu_item
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :orders
  has_many :menu_items, through: :orders

  def total
    total=0
    self.menu_items.each do |item|
      total += item.price
    end
  total
  end
  
end

app/models/server.rb
class Server < ActiveRecord::Base
  belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    redirect_to log_in_path
  end

  def new
    @admin = Admin.new
  end

  def create
    Admin.create( admin_params )
    redirect_to root_path
  end

  def profile
    current_user
    @menuitems = MenuItem.all
    @menuitem = MenuItem.new
    @servers = Server.all
    @server = Server.new
  end

  def log_in

  end

  private
  def admin_params
    params.require(:admin).permit(:username, :password)
  end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

    before_action :authenticate!

    def index
      redirect_to log_in_path
    end

    def create
      menuitem = MenuItem.create(menu_item_params)
      redirect_to profile_path
    end

    def edit
      @menuitem = MenuItem.find(params[:id])
    end

    def destroy
      MenuItem.destroy(params[:id])
      redirect_to profile_path
    end

    def show
      @menuitem = MenuItem.params[:id]
    end

    private

    def menu_item_params

      parameters = params.require(:menu_item).permit(:category, :price, :name)

    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

      def bar
        drinkorders = Order.where(done: nil)
        @items = MenuItem.where(category: "Drinks").order("created_at desc")
        @menuitems = MenuItem.all

        @drinks = []
        drinkorders.each do |drinkorder|
          @items.each do |item|
            if drinkorder.menu_item_id == item.id
            @drinks.push(drinkorder)
            end
          end
        end
      end

      def kitchen
        foodorders = Order.where(done: nil)
        @items = MenuItem.where.not(category: "Drinks").order("created_at desc")
        @menuitems = MenuItem.all

        @eats = []
        foodorders.each do |foodorder|
          @items.each do |item|
            if foodorder.menu_item_id == item.id
            @eats.push(foodorder)
            end
          end
        end
      end

      def new
        @order = Order.new
      end

      def create
        party = Party.find(params[:party_id])
        party.orders.create(order_params)

        redirect_to party_path(party)
      end

      def edit
        order = Order.find(params[:id])
        order.update(order_params)
        redirect_to orders_bar_path
      end

      def update
        order = Order.find(params[:id])
        order.update (order_params)

        redirect_to :back

      end

      def show
        @order = Order.params[:id]
      end


      private

      def order_params

      params.require(:order).permit(:party_id, :menu_item_id, :done)

      end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def index
    @parties = Party.where(closed: nil)
    @party = Party.new
    @servers = Server.all
  end

  def checks
    @parties = Party.where(closed: nil)
  end

  def split
    @menu_items = MenuItem.all
    @current_party = Party.find(params[:id])

    new_party = Party.find_by(server_id: nil, closed: nil)

    if (new_party && (new_party.id != @current_party.id))
      @new_party = new_party
    else
      @new_party = Party.create()
    end

  end

  def create
    party = Party.create(party_params)
    redirect_to parties_path
  end

  def edit
    @party = Party.find(params[:id])
  end

  def show
    @party = Party.find(params[:id])
    @orders = @party.orders
    @order = @party.orders.new

  end
  def update
    party = Party.find(params[:id])
    party.update (party_params)
    redirect_to parties_checks_path
  end

  private

  def party_params

    params.require(:party).permit(:guest_num, :table_num, :server_id, :closed)

  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  before_action :authenticate!

  def create
    server = Server.create(server_params)
    redirect_to profile_path
  end

  def edit
    @server = Server.find(params[:id])
  end

  def show
    @server = Server.params[:id]
  end
  def destroy
    Server.delete(params[:id])
    redirect_to profile_path
  end
  private
  def server_params
    parameters = params.require(:server).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    admin = Admin.find_by_username(params[:username])
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to profile_path
    else
      redirect_to root_path
    end
end
  def destroy
    session[:admin_id] = nil
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:admin_id]
      @current_user = @current_user || Admin.find(session[:admin_id])
    end
  end

  def authenticate!
    redirect_to log_in_path unless current_user
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/log_in.html.erb
<%= form_tag(sessions_path, :class => "active")  do %>
<div class="row">
  <div class="col s4 push-s2">
    <%= text_field_tag :username %>
    <%= label_tag :username %>
  </div>
  <div class="col s4 push-s2">
    <%= password_field_tag :password %>
    <%= label_tag :password %>
  </div>
</div>
<div class="row">
  <div class="col s4 push-s4">
    <%= submit_tag "Log In", class: "waves-effect waves-light btn"  %>
  </div>
</div>
<% end %>

app/views/admins/new.html.erb
<h3> Sign Up </h3>
<%= form_for @admin do |f| %>
 <%= f.label :username %>
 <%= f.text_field :username %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%= f.submit %>
<% end %>

app/views/admins/profile.html.erb
<h1> <%= current_user.username %> </h1>
<%= button_to "Log-Out", sessions_path, method: :delete, class: "waves-effect waves-light btn" %><br><br>



<h4>Add New Item</h4>
<%= form_for @menuitem, url: admin_menu_items_path(current_user), :html => {:class => 'active'} do |f| %>
<div class="row">
  <div class="col s4 push-s2">
    <%= f.text_field :category %>
    <%= f.label :category %>
  </div>
  <div class="col s4 push-s2">
    <%= f.number_field :price, :class => 'text_field', :step => 'any' %>
    <%= f.label :price %>
  </div>
</div>
<div class="row">
  <div class="col s4 push-s2">
    <%= f.text_field :name %>
    <%= f.label :name %>
  </div>
  <div class="col s4 push-s2">
    <%= f.submit "Create Item", class: "waves-effect waves-light btn" %>
  </div>
</div>
<% end %>
​

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Price</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @menuitems.each do |item| %>
    <tr>
      <td><%= item.category %></td>
      <td><%= '%.2f' % item.price %></td>
      <td><%= item.name %></td>
      <td><%= button_to "Delete", item, :method => :delete %></td>

    </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= form_for @server, url: admin_servers_path(current_user) do |f| %>
<div class="row">
  <div class="col s4 push-s2">
    <%= f.text_field :name %>
    <%= f.label :name %>
  </div>
  <div class="col s4 push-s2">
    <%= f.submit "Hire Server", class: "waves-effect waves-light btn" %>
  </div>
</div>
<% end %>

<ul>
  <%@servers.each do |server| %>
  <li><%=server.name%><%= button_to "delete", server, :method => :delete %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurantapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css" media="screen" title="no title" charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js" charset="utf-8"></script>
</head>
<body class="container">
  <nav>
    <div class="nav-wrapper teal ">
      <a href="/parties" class="brand-logo center hide-on-small-and-down">Restaurante</a>
      <ul class="left ">
        <li><a href="/parties">Parties</a></li>
        <li><a href="/admins">Admins</a></li>
      </ul>
      <ul class="right">
        <li><a href="/parties/checks/">Checks</a></li>
        <li><a href="/orders/bar/">Bar</a></li>
        <li><a href="/orders/kitchen/">Kitchen</a></li>
      </ul>
    </div>
  </nav>
<%= yield %>
</body>
</html>