config/routes.rb
Rails.application.routes.draw do
get '/parties/checks/' => 'parties#checks'
get '/parties/:id/split/' => 'parties#split'

  resources :parties do
    resources :orders
  end

  resources :admins do
    resources :servers
    resources :menu_items
  end

  resources :menu_items
  resources :servers

  get '/orders/kitchen' => 'orders#kitchen'
  get '/orders/bar' => 'orders#bar'
  get '/menu_items' => 'admins#log_in'
  get '/servers' => 'admins#log_in'
  get '/log_in' => 'admins#log_in'
  post '/sessions/' => 'sessions#create'

  delete '/sessions/' => 'sessions#destroy'
  get '/profile' => 'admins#profile'
  resources :orders
  root 'parties#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  has_many :menuitems
  has_many :servers
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :admin
  has_many :orders, dependent: :destroy
  has_many :parties, through: :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :party
  belongs_to :menu_item
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :orders
  has_many :menu_items, through: :orders

  def total
    total=0
    self.menu_items.each do |item|
      total += item.price
    end
  total
  end
  
end

app/models/server.rb
class Server < ActiveRecord::Base
  belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    redirect_to log_in_path
  end

  def new
    @admin = Admin.new
  end

  def create
    Admin.create( admin_params )
    redirect_to root_path
  end

  def profile
    current_user
    @menuitems = MenuItem.all
    @menuitem = MenuItem.new
    @servers = Server.all
    @server = Server.new
  end

  def log_in

  end

  private
  def admin_params
    params.require(:admin).permit(:username, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include ApplicationHelper
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

    before_action :authenticate!

    def index
      redirect_to log_in_path
    end

    def create
      menuitem = MenuItem.create(menu_item_params)
      redirect_to profile_path
    end

    def edit
      @menuitem = MenuItem.find(params[:id])
    end

    def destroy
      MenuItem.destroy(params[:id])
      redirect_to profile_path
    end

    def show
      @menuitem = MenuItem.params[:id]
    end

    private

    def menu_item_params

      parameters = params.require(:menu_item).permit(:category, :price, :name)

    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

      def bar
        drinkorders = Order.where(done: nil)
        @items = MenuItem.where(category: "Drinks").order("created_at desc")
        @menuitems = MenuItem.all

        @drinks = []
        drinkorders.each do |drinkorder|
          @items.each do |item|
            if drinkorder.menu_item_id == item.id
            @drinks.push(drinkorder)
            end
          end
        end
      end

      def kitchen
        foodorders = Order.where(done: nil)
        @items = MenuItem.where.not(category: "Drinks").order("created_at desc")
        @menuitems = MenuItem.all

        @eats = []
        foodorders.each do |foodorder|
          @items.each do |item|
            if foodorder.menu_item_id == item.id
            @eats.push(foodorder)
            end
          end
        end
      end

      def new
        @order = Order.new
      end

      def create
        party = Party.find(params[:party_id])
        party.orders.create(order_params)

        redirect_to party_path(party)
      end

      def edit
        order = Order.find(params[:id])
        order.update(order_params)
        redirect_to orders_bar_path
      end

      def update
        order = Order.find(params[:id])
        order.update (order_params)

        redirect_to :back

      end

      def show
        @order = Order.params[:id]
      end


      private

      def order_params

      params.require(:order).permit(:party_id, :menu_item_id, :done)

      end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def index
    @parties = Party.where(closed: nil)
    @party = Party.new
    @servers = Server.all
  end

  def checks
    @parties = Party.where(closed: nil)
  end

  def split
    @menu_items = MenuItem.all
    @current_party = Party.find(params[:id])

    new_party = Party.find_by(server_id: nil, closed: nil)

    if (new_party && (new_party.id != @current_party.id))
      @new_party = new_party
    else
      @new_party = Party.create()
    end

  end

  def create
    party = Party.create(party_params)
    redirect_to parties_path
  end

  def edit
    @party = Party.find(params[:id])
  end

  def show
    @party = Party.find(params[:id])
    @orders = @party.orders
    @order = @party.orders.new

  end
  def update
    party = Party.find(params[:id])
    party.update (party_params)
    redirect_to parties_checks_path
  end

  private

  def party_params

    params.require(:party).permit(:guest_num, :table_num, :server_id, :closed)

  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  before_action :authenticate!

  def create
    server = Server.create(server_params)
    redirect_to profile_path
  end

  def edit
    @server = Server.find(params[:id])
  end

  def show
    @server = Server.params[:id]
  end
  def destroy
    Server.delete(params[:id])
    redirect_to profile_path
  end
  private
  def server_params
    parameters = params.require(:server).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    admin = Admin.find_by_username(params[:username])
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to profile_path
    else
      redirect_to root_path
    end
end
  def destroy
    session[:admin_id] = nil
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:admin_id]
      @current_user = @current_user || Admin.find(session[:admin_id])
    end
  end

  def authenticate!
    redirect_to log_in_path unless current_user
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/orders/bar.html.erb
<h2>BAR SCREEN</h2>

<ul>
  <% @drinks.each do |drink| %>
<div class="row">
  <div class="col s5 push-s3">
    <% if (((Time.now() - drink.created_at)/60) < 2) %>
      <li class="new-class"><%= drink.menu_item.name %> | Party # <%= drink.party_id %> | <%=time_ago_in_words(drink.created_at) %>
    <% elsif (((Time.now() - drink.created_at)/60) < 4) %>
      <li class="med-class"><%= drink.menu_item.name %> | Party # <%= drink.party_id %> | <%=time_ago_in_words(drink.created_at) %>
    <% else %>
      <li class="hurry-class"><%= drink.menu_item.name %> | Party # <%= drink.party_id %> | <%=time_ago_in_words(drink.created_at) %>
    <% end %>
  </div>
  <div class="s1">
        <%=form_for drink, url: order_path(drink) do |f| %>
        <%=f.hidden_field :done, :value => true %>
        <%=f.submit "✓"%>
        <% end %>
      </li>
  </div>
</div>
<% end %>
</ul>

app/views/orders/kitchen.html.erb
<h1>Kitchen SCREEN!!</h1>

<ul>
  <% @eats.each do |eat| %>
<div class="row">
<div class="col s5 push-s3">
  <% if (((Time.now() - eat.created_at)/60) < 7) %>
    <li class="new-class"><%= eat.menu_item.name %> Party #<%= eat.party_id %> | <%= time_ago_in_words(eat.created_at) %>
    <% elsif (((Time.now() - eat.created_at)/60) < 12) %>
    <li class="med-class"><%= eat.menu_item.name %> Party #<%= eat.party_id %> | <%= time_ago_in_words(eat.created_at) %>
    <% else %>
    <li class="hurry-class"><%= eat.menu_item.name %> Party #<%= eat.party_id %> | <%= time_ago_in_words(eat.created_at) %>
    <% end %>
  </div>
  <div class="s1">
    <%=form_for eat, url: order_path(eat) do |f| %>
    <%=f.hidden_field :done, :value => true %>
    <%=f.submit "✓"%>
    <% end %>
    </li>
  </div>
</div>
<% end %>
</ul>

app/views/parties/checks.html.erb
<h2>Open Checks</h2>

<div class="row">
    <% @parties.each do |party|%>
    <div class="col s12 m6 l4" id="check">
      <ul>
        <li><strong>Check for Party # <%= party.id %></strong></li>
        <%party.menu_items.each do |item|%>
          <li><%= item.name %> :<div class="right"><%= '%.2f' % item.price %></div></li>
          <% end%>
          <li><div class="right">Subtotal: $<%= '%.2f' % party.total() %></div></li><br>
          <li><div class ="right">Tax: $<%= '%.2f' % (party.total()*0.0875) %></div></li><br>
          <li><div class ="right">Total: $<%= '%.2f' % (party.total()*1.0875) %></div></li>
          <li><%=form_for party, url: party_path(party) do |f| %>
            <%=f.hidden_field :closed, :value => true %>
            <%=f.submit "Close Check"%>
            <% end %>
          </li>
          <li><a href="/parties/<%=party.id%>/split">Split Check</a></li><br>
          <li><div class ="right">15% gratuity add $<%= '%.2f' % (party.total()*0.15) %></div></li><br>
          <li><div class ="right">20% gratuity add $<%= '%.2f' % (party.total()*0.20) %></div></li><br>
          <li><div class ="right">25% gratuity add $<%= '%.2f' % (party.total()*0.25) %></div></li>
      </ul>
    </div>
    <% end %>
</div>

app/views/parties/index.html.erb
<div class="row">
  <div class="column s12">
    <h1>Party Management</h1>
  </div>

<div class="row">
  <div class="col s8 push-s2">
    <div class="collection">
      <% @parties.each do |party| %>
      <a href="/parties/<%=party.id%>" class="collection-item">Server :
        <% if party.server_id %>
        <%= @servers[party.server_id-1].name %>
      
        <% end %>
        : Party # <%= party.id %> : <%= party.guest_num%> Guests</a>
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <%= form_for @party, :html => {:class => "col s12"} do |f| %>
    <div class="row">
      <div class="col s2 push-s2">
        <%= f.number_field :guest_num, class: "active", :placeholder => "Guests" %>
      </div>
      <div class="col s2 push-s2">
        <%= f.collection_select :server_id, Server.all, :id, :name, { prompt: "Server Name"}, class: "browser-default" %>
      </div>
      <div class="col s2 push-s2">
        <%= f.number_field :table_num, :placeholder => "Table Number"  %>
      </div>
      <div class="col s2 push-s2">
        <%= f.submit "New Party", class: "waves-effect waves-light btn" %>
      </div>
      <% end %>
    </div>

</div>

app/views/parties/new.html.erb
<%= form_for @party do |f| %>
  <%= f.label :guest_num, "Guests:" %>
  <%= f.number_field :guest_num %>
  <%= f.collection_select :server_id, Server.all, :id, :name, include_blank: true %>
  <%= f.label :table_num, "Table Number:" %>
  <%= f.number_field :table_num %>
  <%= f.submit %>
<% end %>

app/views/parties/show.html.erb
<h4>Party: <%=@party.id %> Table: <%= @party.table_num%></h3>
<div class="row">
  <div class="input-field col s8 push-s2">
    <%= form_for @order, url: party_orders_path(@party) do |f| %>
      <div class="col s4 push-s2">
        <%= f.collection_select :menu_item_id, MenuItem.all, :id, :name,{ prompt: "Place order"}, class: "browser-default"%>
      </div>
      <div class="col s4 push-s2">
        <%= f.submit "Order", class: "waves-effect waves-light btn" %>
      </div>
  </div>
  <% end %>
</div>



<table class="party-show" class="bordered">
  <thead>
    <tr>
      <th>Price</th>
      <th>Name</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @party.menu_items.each do |item| %>
    <tr>
      <td><%= '%.2f' % item.price %></td>
      <td><%= item.name %></td>
      <td><%= item.category %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<h4>Subtotal: $<%= '%.2f' % @party.total() %></h4>
<h4>Tax: $<%= '%.2f' % (@party.total()*0.0875) %></h4>
<h4>Total: $<%= '%.2f' % (@party.total() * 1.0875) %></h4>

app/views/parties/split.html.erb
<div class="row">
  <div class="col s6">
    <h1>Table # <%= @current_party.id%> </h1>
    <ul>
    <% @current_party.orders.each do |order| %>
    <li><%=order.menu_item.name%></li>
    <li><%= form_for order, url: order_path(order) do |f| %>
    <%=f.hidden_field :party_id, :value => @new_party.id %>
    <%=f.submit "✓"%>
    <% end %>
    </li>
    <% end %>
    </ul>
  </div>
  <div class="col s6">
    <h1>Table # <%= @new_party.id%> </h1>
    <ul>
    <% @new_party.orders.each do |order| %>
    <li><%= order.menu_item.name %></li>
    <% end %>
    </ul>


  </div>
</div>
<ul>

app/views/servers/index.html.erb
<ul>
<% @servers.each do |server| %>
<li><%= server.id %> : <%= server.name %></li>

</ul>
<% end %>

<%= form_for @server do |f| %>
  <%= f.label "Server Name"%>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>